//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StutentsKyrs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distiplines
    {
        public Distiplines()
        {
            this.Evaluation = new HashSet<Evaluation>();
        }
    
        public int Id { get; set; }
        public string Title_ { get; set; }
        public Nullable<int> Teatcher { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Evaluation> Evaluation { get; set; }

        public override string ToString()
        {
            return Title_;
        }
    }
}
